[package]
name = "hoshiepub"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "hoshiepub"

[dependencies]
rbook = { version = "0.7.10", default-features = false, features = ["threadsafe"] }
thiserror = "2"
uniffi = { version = "0.28", features = ["cli"] }
uniffi_bindgen = "0.28" # Match the version of uniffi you are using

[features]
bindgen = ["uniffi/cli"]
